sick_lists_homepage:
    path:     /
    defaults: { _controller: SickListsBundle:Lists:index }

sick_lists_postitem:
    path:   /items/new
    defaults: { _controller: SickListsBundle:Lists:addItem }
    methods: [POST]

sick_lists_postproject:
    path: /projects/new
    defaults: { _controller: SickListsBundle:Project:addProject }
    methods: [POST]

sick_lists_show_project:
    path: /projects/{id}
    defaults: { _controller: SickListsBundle:Project:showProject }
    methods: [GET]
    requirements:
        id: \d+
