parameters:
#    sick_lists.example.class: Sick\Bundle\ListsBundle\Example

services:
#    sick_lists.example:
#        class: %sick_lists.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
